## Testing data with *Random Forest Classifier* Model

In [ ]:
# from google.colab import drive
# drive.mount('/content/drive')

In [1]:
# Import basic libraries
import pandas as pd
import numpy as np
import pickle

In [2]:
# Load the model
with open('/Users/rafaelaqueiroz/Sentiment-Analysis-of-Medication-Reviews-Project/rfc_model.pkl', 'rb') as file:
    rfc_model = pickle.load(file)

In [3]:
print(rfc_model)

Pipeline(steps=[('vect', CountVectorizer()), ('tfidf', TfidfTransformer()),
                ('clf',
                 RandomForestClassifier(class_weight={0: 2, 1: 1, 2: 1},
                                        random_state=42))])


In [5]:
# Define the review_text variable
review_text_1 = "I did not like this pill"
rfc_model.predict([review_text_1])

array([0])

In [6]:
review_text_2 = "I like this pill"
rfc_model.predict([review_text_2])

array([2])

In [7]:
review_text_3 = "This pill is horrible"
rfc_model.predict([review_text_3])

array([0])

In [8]:
review_text_4 = "I got sick and sad"
rfc_model.predict([review_text_4])

array([0])

In [9]:
review_text_5 = "This patch is perfect"
rfc_model.predict([review_text_5])

array([2])

In [12]:
# Example retrieved from X_test[1] and it should be predicted as positive
example_1 = "My son has Crohn&#039;s disease and has done very well on the Asacol. He has no complaints and shows no side effects.  He has taken as many as nine tablets per day at one time.  I&#039;ve been very happy with the results, reducing his bouts of diarrhea drastically."
rfc_model.predict([example_1])

array([2])

In [13]:
# Example retrieved from X_test[10] and it should be predicted as negative
example_2 = "Holy Hell is exactly how I feel. I had been taking Brisdelle for 1.5 years. The hot flashes did indeed subside - however, the side affects of this medicine coupled with the fact Noven was acquired by YET another pharmaceutical company - YOU CAN&#039;T PLACE A REP IN THE AREA, DISTRIBUTE YOUR DRUGS, AND THEN FIRE HER-AND NOT REPLACE THEREFORE there is NO medicine or support here. You dumped this drug in the Dr&#039;s hands and walked away. After calling Sebula - you act like you don&#039;t even care. You have made it impossible to obtain this. I happen to think this is illegal. I just decided to wean myself off this and Premarin. It has been nothing short of a nightmare. If you don&#039;t need this drug- DON&#039;T START. Seriously."
rfc_model.predict([example_2])

array([0])

In [15]:
# Example retrieved from X_test[20] and it should be predicted between negative or neutral (the last might be because of the end recommendation)
example_3 = "If I could give it a 0, I would absolutely do so.  Started at 50mg, and felt WIRED.  Wanted to get up and clean the house!  Bumped it to 100mg, less wired, but still wide awake all night.  Bumped to 150, with the same lack of effect.  MD informed me after this dose it becomes less effective for sleep, so why even bother.  15 years of trying different sleep medications and alternatives, and this, I can say for sure, was the LEAST effective I have ever come across.  At it&#039;s low price point, feel free to give it a try, and maybe you will be luckier?  Everyone&#039;s sleep conditions are different.  But if you get hyper after benadryl, expect the same reaction to this drug."
rfc_model.predict([example_3])

array([2])

In [16]:
# Example retrieved from X_test[200] and it should be predicted as negative
example_4 = "Took levofloxin for pneumonia and cleared up quick. Within 2 months my achilles was sore everyday. Made an appointment with a podiatrist for Nov 17th. Achilles snapped on Nov 14th. Surgery went well to repair shredded achilles. In cast for 3 months. Since sore after 3 months on my feet and working. I nurse it everyday. Avoid this drug, if possible. Not worth the side effects."
rfc_model.predict([example_4])

array([2])

In [17]:
# Example retrieved from X_test[3] and it should be predicted as positive
example_5 = "Contrave combines drugs that were used for alcohol, smoking, and opioid cessation. People lose weight on it because it also helps control over-eating. I have no doubt that most obesity is caused from sugar/carb addiction, which is just as powerful as any drug. I have been taking it for five days, and the good news is, it seems to go to work immediately. I feel hungry before I want food now. I really don&#039;t care to eat; it&#039;s just to fill my stomach. Since I have only been on it a few days, I don&#039;t know if I&#039;ve lost weight (I don&#039;t have a scale), but my clothes do feel a little looser, so maybe a pound or two. I&#039;m hoping that after a few months on this medication, I will develop healthier habits that I can continue without the aid of Contrave."
rfc_model.predict([example_5])

array([2])

In [18]:
# Example retrieved from X_test[0] and it should be predicted as positive
example_6 = "I&#039;ve tried a few antidepressants over the years (citalopram, fluoxetine, amitriptyline), but none of those helped with my depression, insomnia &amp; anxiety. My doctor suggested and changed me onto 45mg mirtazapine and this medicine has saved my life. Thankfully I have had no side effects especially the most common - weight gain, I&#039;ve actually lost alot of weight. I still have suicidal thoughts but mirtazapine has saved me."
rfc_model.predict([example_6])

array([2])

In [19]:
# Example retrieved from X_test[6] and it should be predicted as "neutral"
example_7 = "I&#039;ve had the copper coil for about 3 months now. I was really excited at the thought of not taking hormones. I&#039;m good with pain however I nearly fainted with insertion, couldn&#039;t belive how painful it was; the doctor did say it is very painful for some. Well 3 months in, my periods last 11 days and I&#039;m in pain for about 15 days with random twangs especially in the left side and I&#039;m considering whether I want to put up with the intense pain and heavy periods. I&#039;d recommend this 100% to somebody who doesn&#039;t already have heavy painful periods but right now it just isn&#039;t for me"
rfc_model.predict([example_7])

array([2])

In [21]:
# Example retrieved from X_test[187] and it should be predicted as positive
example_8 = "'I was prescribed valium for tension headaches. I have severe migraines and tension headaches. They could not find out exactly why I was having them, so we have to treat the symptom. Valium actually makes me able to function through some of the worst tension headaches. Before, I was spending so much time locked in a dark room between the migraines and tension headaches. I was missing my lfe and the lives of my children. It is really nice to be able to have a part in their lives and my own. I am thankful daily that I can rejoin the world again."
rfc_model.predict([example_8])

array([2])

In [23]:
# Example retrieved from X_test[22] and it should be predicted as negative
example_9 = "After a few days and it &quot;kicked in,&quot; every noise in the house would make me jump, pictures on TV would feel as if they were 3-D and make me jump, and I literally felt like my skin was crawling, moving, and melding to things, such as blankets. My mind focused and keyed in on every piece of white noise there was and I had sweaty, night hot flashes with chills."
rfc_model.predict([example_9])


array([2])

In [24]:
# Example retrieved from X_test[29] and it should be predicted as positive
example_10 = "I am a 25 year old female. I was diagnosed with bipolar II disorder about 5 years ago. I have been taking 150mg of lamotrigine for over 2 years. Thus far I have experienced significant improvements in controlling my bipolar II disorder. I recently paired 100mg of sertraline to improve the lows. Also, I experience rapid cycling. I rated this drug 70% as I feel I still have a long way to go in recovery. But, the drug has definitely allowed me to be a highly functioning individual."
rfc_model.predict([example_10])             

array([2])